version: '3.8'

services:
  backend:
    build: .
    container_name: telecom-form-ahvaan
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
