services:
  backend:
    build: .
    container_name: telecom-form-ahvaan
    ports:
      - "5000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules

# volumes:
#   node_modules: